name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/node

      - name: Setup just
        uses: ./.github/actions/just
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: just install ci

      - name: Build
        run: just build ci

      - name: Test
        run: just test ci

      - name: Check for uncommitted changes
        run: just chore check-clean

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/node

      - name: Setup just
        uses: ./.github/actions/just
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: just install ci

      - name: Format
        run: just chore format-ci
